name: Deploy prod

on:
  # Trigger the action manually from the UI
  workflow_dispatch:
  # Trigger the action when I create or push a `release/**` branch
  push:
    branches:
      - 'main'
  pull_request:
    branches: 
      - 'main'

env:
  TFM_ACCESS_KEY: ${{ secrets.TFM_ACCESS_KEY }}
  TFM_SECRET_KEY: ${{ secrets.TFM_SECRET_KEY }}
  TF_VAR_token: ${{ secrets.YA_TKN }}
  TF_VAR_cloud_id: ${{ secrets.YA_CLOUD_ID }}
  TF_VAR_folder_id: ${{ secrets.YA_FOLDER_ID }}

jobs:
  deploy_terraform:
    name: Deploy kubernetes cluster
    environment: prod
    # Runner to use
    runs-on: notebook

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    # - name: terraform init
    #   run: |
    #     cd ./terraform-init
    #     terraform init -backend-config="access_key=$TFM_ACCESS_KEY" -backend-config="secret_key=$TFM_SECRET_KEY"
    #     terraform plan
    #     terraform apply -auto-approve
    
    - name: terraform kuber init
      run: |
        cd ./kuber-init
        terraform init -backend-config="access_key=$TFM_ACCESS_KEY" -backend-config="secret_key=$TFM_SECRET_KEY"

    - name: terraform kuber plan
      run: |
        ls -la
        cd ./kuber-init
        terraform plan
        terraform apply -auto-approve
        
    - name: kuber deploy
      run: |
        ls -la
        ./kuber-init/ansible/kubespray.sh

  check_deploy:
    needs: deploy_terraform
    name: Check deploy terraform
    runs-on: notebook

    steps:
      - name: copy kubeconfig
        run: |
          kubectl get pods --all-namespaces
