name: Init terraform state storage

on:
  # Trigger the action manually from the UI
  workflow_dispatch:

env:
  TFM_ACCESS_KEY: ${{ secrets.TFM_ACCESS_KEY }}
  TFM_SECRET_KEY: ${{ secrets.TFM_SECRET_KEY }}
  TF_VAR_token: ${{ secrets.YA_TKN }}
  TF_VAR_cloud_id: ${{ secrets.YA_CLOUD_ID }}
  TF_VAR_folder_id: ${{ secrets.YA_FOLDER_ID }}

jobs:
  deploy_terraform_s3:
    name: Create terraform state storage s3
    environment: prod
    # Runner to use
    runs-on: notebook

    steps:
    - name: checkout code
      uses: actions/checkout@v4
    
    - name: terraform init
      run: |
        cd ./terraform-init
        terraform init -backend-config="access_key=$TFM_ACCESS_KEY" -backend-config="secret_key=$TFM_SECRET_KEY"

    - name: terraform apply
      run: |
        cd ./terraform-init
        terraform plan
        terraform apply -auto-approve